### ISSUE TITLE
Monitor paths different

### ISSUE THREAD

**Issue by everyonce** [goruck/smart-zoneminder#4]
My monitor storage is doing directories with the monitor ID (ie, 1,2,3) instead of the names (Monitor-1, etc), so zm-s3-upload is guessing the wrong paths and bombing out.  Is there some setting i didn't do correctly?

**Comment by goruck** [comment]
Hi,

please send me:

1. A log of the error with the logging level set to 'debug'. You can set
the logging level in the configuration file.

2. The version of zomeminder are you using.

3. The setting of USE_DEEP_STORAGE.

I suspect that your issue has to do with number 3 above. zm-s3-upload only
works today with USE_DEEP_STORAGE enabled. Note the setting itself is not
configurable in some versions of zoneminder where it is enabled by default.

I'll take a look at the logs and will figure out what's going on. The
function 'buildFilePath' figures out the path to the images based on the
configuration and the MySQL queries but again will only work today
with USE_DEEP_STORAGE
enabled.

Thanks.

**Comment by everyonce** [comment]
my default storage was set to Medium, zoneminder version 1.32.3
I changed the setting on the storage to do deep storage, but it didn't change the types of paths it is using.  is USE_DEEP_STORAGE a setting i have to add to zm.conf??  I don't see it in any of the config files.

Here's the logs from zm-s3-upload:
```Logger created...
info: Waiting for first alarm frames...
debug: Getting more frames to process.
debug: Getting more frames to process.
debug: Getting more frames to process.
debug: Getting more frames to process.
debug: Getting more frames to process.
info: 1 un-uploaded frames found in: 326 milliseconds
debug: aryRows len: 1 maxInit: 1 isComplete: false
info: Running with remote object detection enabled.
debug: Alarm frame info: RowDataPacket {
  frameid: 2,
  frame_timestamp: 2018-12-29T15:53:50.000Z,
  score: 255,
  frame_delta: 0.65,
  event_name: 'New Event',
  starttime: 2018-12-29T15:53:49.000Z,
  monitor_name: 'Monitor-1',
  upload_timestamp: null,
  eventid: 29570,
  image_base_path: '/var/lib/zoneminder/events/' }
error: remoteObjDetect error: Error: upload error: Error: ENOENT: no such file or directory, open '/var/lib/zoneminder/events//Monitor-1/18/12/29/09/53/49/00002-capture.jpg'
```

For what it's worth - zm has put the file here:
```/var/lib/zoneminder/events/1/18/12/29/09/53/49/00002-capture.jpg```

**Comment by goruck** [comment]
Thanks for the quick update. It looks like the problem is related to not
using deep storage. Based on the logs everything else seems to be ok.

I believe the USE_DEEP_STORAGE option was deprecated in the most current
release and was moved to the storage configuration which you are using.

I'm not sure why changing the storage to deep didn't change the paths. You
should have restarted zoneminder after changing the storage option and you
may have to run zmaudit. See this:
https://forums.zoneminder.com/viewtopic.php?t=27659.

Note that I am working to support both deep and medium storage options (as
well as to move away from directly accessing the filesystem and using the
zm apis if possible).  Support of medium storage should be pretty simple
and quick and will have that available probably next week if you want to
wait.

Let me know how you progress in the meantime.

**Comment by goruck** [comment]
I just noticed from your debug info that there may be something else going
on with the way the latest versions of zoneminder handles monitor names.
Let me do a little debugging on my end. Btw looks like deep paths are
working for you.

**Comment by everyonce** [comment]
I did find this post - looks like it might be a permanent change on all the storage options:
https://forums.zoneminder.com/viewtopic.php?f=38&t=27664

**Comment by goruck** [comment]
Thanks. It does look like you are using deep storage then.

Further looking at your log and the code I see two problems. 1) you have a
trailing '/' on the image base path which is not needed. 2) the monitor
name looks like it's being stored differently in the database now which
results in a bad image path being generated. The code should just use the
number of the monitor and not the entire name. I'm not sure why that
changed from the version 1.30 I tested with. I will verify that and make
the fix if it turns out to be the case. But you should also modify your
base path name and remove the trailing /.

Thanks.

**Comment by goruck** [comment]
I did some more checks on my system and I think if you drop the trailing
'/' from the base image path it should work.

On my system zoneminder creates a symlink between the monitor name and the
monitor id. So in your case you should see a symlink between Monitor-1 and
a directory called 1 in your image base path directory. If this exists then
zm-s3-upload should find your images.

Pls give that a try and lmk what you find out.

Thanks.

**Comment by everyonce** [comment]
Alright - so it didn't create those symlinks.  Maybe I should try creating a new "storage" and see if it creates those?

```root@zoneminder:/var/lib/zoneminder/events# ls -lah
total 24K
drwxrwxrwx 6 www-data www-data 4.0K Dec 29 09:51 .
drwxrwxrwx 3 www-data www-data 4.0K Dec 23 20:20 ..
drwxr-xr-x 3 www-data www-data 4.0K Dec 29 09:51 1
drwxr-xr-x 3 www-data www-data 4.0K Dec 29 09:51 2
drwxr-xr-x 3 www-data www-data 4.0K Dec 29 09:51 3
drwxr-xr-x 3 www-data www-data 4.0K Dec 29 09:51 4
root@zoneminder:/var/lib/zoneminder/events#
```

**Comment by everyonce** [comment]
You are correct - I did the rename and it created the symlink:

```root@zoneminder:/var/lib/zoneminder/events# ls -lah
total 24K
drwxrwxrwx 6 www-data www-data 4.0K Dec 30 09:05 .
drwxrwxrwx 3 www-data www-data 4.0K Dec 23 20:20 ..
drwxr-xr-x 3 www-data www-data 4.0K Dec 29 09:51 1
drwxr-xr-x 3 www-data www-data 4.0K Dec 29 09:51 2
drwxr-xr-x 3 www-data www-data 4.0K Dec 29 09:51 3
drwxr-xr-x 3 www-data www-data 4.0K Dec 29 09:51 4
lrwxrwxrwx 1 www-data www-data    1 Dec 30 09:05 FrontPorchDome -> 4
root@zoneminder:/var/lib/zoneminder/events#
```
